changelog:
  exclude:
    labels:
      - ignore-for-release
      - internal
    authors:
      - github-actions[bot]
      - dependabot[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Added
      labels:
        - feature
        - enhancement
    - title: Fixed
      labels:
        - fix
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
